// FILM.TIMELINE: the shot list and audio cue list for "One burger, two prices".
// Owner: storyboard. Human-readable plan: docs/storyboard.md. Visual rules: docs/art-bible.md.
// 120 bpm: a beat is 0.5 s (12 frames at 24 fps), a 16th 0.125 s (3 frames). Every shot boundary sits on the
// 0.5 s grid; every cue sits on the 16th grid. 18 shots tile 0..32 s (768 frames); the hinge is T 16.0.
(function () {
  'use strict';
  const FILM = window.FILM;
  const cut = { kind: 'cut', dur: 0 };

  FILM.TIMELINE = {
    title: 'One burger, two prices',
    bpm: 120,
    duration: 32,
    fps: 24,
    width: 1080,
    height: 1920,
    shots: [
      {
        id: 'booth-569',
        file: '01-booth-569.js',
        start: 0,
        end: 2,
        mode: 'illustrated',
        title: 'Cold open: the $5.69 booth',
        transitionIn: cut,
        brief: `G1 on the modest street: white sky, the booth on the right with its BURGERS sign, flower and white awning and the hanging $5.69 tag, the owner bored in the window, a small yellow house and picket fence on the left. Frame 0 is fully drawn with the hero's front wheel entering at the left edge; he rolls to the G1 stop mark and skids on 0.5, holds up two coins on 1.0 and slaps them on the counter on 1.5 with an impact star. Camera locked, the tag rocks 2 degrees on twos. Same pixels as 15 and 18; 18's last frame loops into this frame 0.`,
      },
      {
        id: 'owner-serves',
        file: '02-owner-serves.js',
        start: 2,
        end: 3.5,
        mode: 'schematic',
        title: 'Inside booth one: the owner serves',
        transitionIn: cut,
        brief: `G2: inside booth one, the camera behind the counter looking out through the window at the modest street and the hero's beaming face; the tired owner three-quarter from behind in the left foreground, dense warm wall around the window. The owner pushes the burger to the sill (2.0 to 2.25), the hero snatches it on ones at 2.5, and at 3.0 the owner rakes the coins into the register: the drawer shoots out with a ka-ching. Same interior pixels as 08 and 13.`,
      },
      {
        id: 'first-bite',
        file: '03-first-bite.js',
        start: 3.5,
        end: 6,
        mode: 'illustrated',
        title: 'The first bite',
        transitionIn: cut,
        brief: `G5 and G4: the hero from the chest up, mouth wide open with the burger raised (frame 0, the same pose that opens 09 and 17), the $5.69 tag at the upper right, the modest street behind, the caption slot empty. Chomp on ones on the 4.0 downbeat (a crescent bite, crumbs, an impact star), chewing on 8ths, bliss at 5.0 with eyes shut as arcs and two held sways, held to the cut.`,
      },
      {
        id: 'title-card',
        file: '04-title-card.js',
        start: 6,
        end: 8,
        mode: 'illustrated',
        title: 'Title: one burger, two prices',
        transitionIn: cut,
        brief: `Light title card: white field with pale titleSpot and titleSpotPink blots, hand-lettered puffy capitals in titleBlue with ink outlines and titleYellow first letters, baselines jumping letter to letter: ONE on frame 0, BURGER, at 6.125, TWO at 6.25, PRICES at 6.375, each popping with outBack. The byline Reuters, Sept 29, 2026 draws on in ink at 6.5 and a whole burger at the bottom bounces once at 7.0. No price appears on this card.`,
      },
      {
        id: 'ride-fence',
        file: '05-ride-fence.js',
        start: 8,
        end: 10,
        mode: 'illustrated',
        title: 'Mile 0: picket fences',
        transitionIn: cut,
        brief: `Static street on the G1 ground line (y 1480): small yellow houses with picket fences, a laundry line, a low skyline. The hero crosses left to right at 700 px/s pedalling on twos, finishing the burger and gulping at 9.0. This file owns the canonical G6 mile counter at the upper left, which pops 0, 0.25, 0.5 and 0.75 mi on the beats.`,
      },
      {
        id: 'ride-fountain',
        file: '06-ride-fountain.js',
        start: 10,
        end: 11.5,
        mode: 'illustrated',
        title: 'Mile 1: a fountain',
        transitionIn: cut,
        brief: `Static street: bigger, plain two-storey pastel houses with no portico, lawns, clipped bushes and a stone fountain whose jets leap on each beat; the skyline rises. The hero crosses left to right and turns his head to the fountain at 10.5. The G6 counter, copied verbatim from 05, pops 1, 1.25 and 1.5 mi.`,
      },
      {
        id: 'ride-columns',
        file: '07-ride-columns.js',
        start: 11.5,
        end: 13,
        mode: 'illustrated',
        title: 'Mile 2: columns',
        transitionIn: cut,
        brief: `Static street: a mansion with four stone columns under a pediment, a long lawn, an urn and an iron gate, the tallest skyline of the trip. The hero crosses left to right; at 12.0 the G6 counter pops 2 mi with a bell, he sniffs and grins at something ahead, and at 12.5 he sprints on the pedals and is gone before the cut.`,
      },
      {
        id: 'booth-again',
        file: '08-booth-again.js',
        start: 13,
        end: 16,
        mode: 'schematic',
        title: 'Inside booth two: the same burger',
        transitionIn: cut,
        brief: `G2 on the same pixels as 02, but the window shows the rich street (stone columns, fountain spray). The hero arrives panting (13.0) and holds up the same coins (13.5); the owner pushes a burger across exactly as in 02 (14.0); the hero snatches it and drops the coins (14.5); the owner taps them twice (15.0, 15.125) and points up at the tag outside (15.25). From 15.417 (shot-local 2.417) to 16.0 a snap push-in on ones over 14 frames, outExpo, from zoom 1 to 6 onto the eye midpoint (562, 790). The tag is never in this frame.`,
      },
      {
        id: 'price-689',
        file: '09-price-689.js',
        start: 16,
        end: 18,
        mode: 'illustrated',
        title: '$6.89',
        transitionIn: cut,
        brief: `Midpoint downbeat: G5 and G4 on the same pixels as 03 with the rich street behind; the tag reads $6.89 and settles, the hero frozen mid-bite looking at it. The eyes pop on stalks at 16.125, a red hand-scrawled +21% appears in the caption slot at 16.25 and the small source note Reuters, Sept 29, 2026 above it at 16.375, the jaw drops at 16.5 and the burger trembles at 17.0. The scene fades itself to ink black over 17.625 to 17.875 and holds black to the end. Reuters could not confirm the gap came from the engine: add no claim that the machine set this price.`,
      },
      {
        id: 'machine-feed',
        file: '10-machine-feed.js',
        start: 18,
        end: 20,
        mode: 'schematic',
        title: 'The pricing machine eats',
        // the second half of the dip to black; the first half is drawn by price-689
        transitionIn: { kind: 'flash', dur: 0.375, color: FILM.lib.pal.ink },
        brief: `Comes up from black. Dense machine room: nightSky back wall under dense strokes, a wall map of red restaurant dots, the G3 machine below (box on legs, hopper on top, periscope retracted, SENSITIVITY TO PRICE gauge, front slot). Seeded streams of receipts and coins leap from the dots and fall into the hopper; white captions nearly 14,000 restaurants (18.25) and millions of orders a day (18.5); the hopper gulps on 19.0 and 19.5. A picture of the analysis, not a real device.`,
      },
      {
        id: 'periscope-view',
        file: '11-periscope-view.js',
        start: 20,
        end: 21,
        mode: 'illustrated',
        title: 'The periscope looks at the street',
        transitionIn: cut,
        brief: `The machine's point of view: a full ink field with a round view (centre 540, 900, radius 400) showing the rich street on the light plate, the stone portico and the fountain. The view pans 450 px from the fountain to the columns over 20.0 to 20.5 and locks with a jolt; the eyelid blinks at 20.875. The G7 caption The engine recommends / an "optimal price" / for each restaurant. pops at 20.25 and stays on the same pixels into 12.`,
      },
      {
        id: 'machine-ticket',
        file: '12-machine-ticket.js',
        start: 21,
        end: 22.5,
        mode: 'schematic',
        title: 'The gauge and the ticket',
        transitionIn: cut,
        brief: `G3 on the same pixels as 10, the periscope raised, the G7 caption still on. On the SENSITIVITY TO PRICE gauge, with based on willingness to pay in your area lettered small under it, the needle crawls from LOW in ratchet steps on 16ths and lands on MEDIUM on 21.5; four print clicks on 16ths (21.75 to 22.125) push a ticket out of the front slot, readable from 22.25: RECOMMENDED: $6.89. The machine recommends; it never sets the price.`,
      },
      {
        id: 'owner-ticket',
        file: '13-owner-ticket.js',
        start: 22.5,
        end: 24,
        mode: 'schematic',
        title: 'The owner gets the ticket',
        transitionIn: cut,
        brief: `G2 on the same pixels as 02 and 08, the rich street in the window, no hero. The ticket flutters in through the window (22.5), the owner catches it (22.75) and holds it up to read RECOMMENDED: $6.89 (23.0); the phone on the counter rings and jumps on 16ths from 23.5. White hand-lettered caption at the top from frame 0: McDonald's: "a tool, not a mandate".`,
      },
      {
        id: 'owner-types',
        file: '14-owner-types.js',
        start: 24,
        end: 26,
        mode: 'schematic',
        title: 'A sigh, then he types the price',
        transitionIn: cut,
        brief: `Dense close-up of the owner: the phone pinned between ear and shoulder, the G4 tag in his hand showing only $, his other hand over a keypad. He listens and nods, sighs on 24.5 (shoulders drop, a sigh puff), then types on 16ths from 25.0 to 25.375 while 6, the point, 8 and 9 appear on the tag; at 25.5 he lifts the finished $6.89. White caption at the lower left from frame 0: Ex-owner: "You don't really have much of a choice anymore."`,
      },
      {
        id: 'turn-back',
        file: '15-turn-back.js',
        start: 26,
        end: 27,
        mode: 'illustrated',
        title: 'Crouch, spin, dash',
        transitionIn: cut,
        brief: `G1 on the same pixels as 01 but on the rich street (portico and fountain behind), the tag reads $6.89, the owner holds the rejected burger out of the window. The hero glares (26.0), crouches (26.25), spins on ones behind a dry-brush smear (26.5) and dashes off the left edge (26.625), leaving speed lines and dust; the tag swings in the gust and the owner blinks.`,
      },
      {
        id: 'ride-back',
        file: '16-ride-back.js',
        start: 27,
        end: 28,
        mode: 'illustrated',
        title: 'Two miles back',
        transitionIn: cut,
        brief: `A cascade of four static 6-frame cards, right to left: the columns (27.0), the fountain (27.25), the fences (27.5), the modest street with booth one (27.75), where the hero skids to a stop. He crosses each card as a smear on ones. The G6 counter, copied from 05, counts down from 1.75 one step per 16th and reaches 0 at 27.875 with a bell.`,
      },
      {
        id: 'bite-again',
        file: '17-bite-again.js',
        start: 28,
        end: 30,
        mode: 'illustrated',
        title: 'Same burger, different neighborhood',
        transitionIn: cut,
        brief: `G5 and G4 on the same pixels as 03 with the modest street behind; the tag reads $5.69 and frame 0 is 03's frame 0. Same burger. pops at 28.25, the chomp lands at 28.5, Different / neighborhood. pops at 28.75, in ink on a titleSpot blob in the caption slot; then chewing, and bliss at 29.5 held to the cut.`,
      },
      {
        id: 'sources-card',
        file: '18-sources-card.js',
        start: 30,
        end: 32,
        mode: 'illustrated',
        title: 'Sources, and the booth again',
        transitionIn: cut,
        brief: `G1 on the same pixels as 01: the modest street, the $5.69 tag, the owner bored in the window, no hero. Hand-lettered sources on titleSpot blobs in the sky zone: Sources: Reuters / CNBC, / Engadget, Restaurant Business / Sept 29 – Oct 1, 2026, a small two-line note Reuters could not confirm the price gap came from the pricing engine., and the channel mark Ideas & Technologies drawing on from 30.5. The owner yawns at 31.0 and is back in 01's frame-0 pose by 31.5, so the last frame loops into 01.`,
      },
    ],
    cues: [
      // Act 1: a burger for $5.69 (F major, puppet-jazz band: pizzicato, xylophone, clarinet-like voice, small cymbal)
      { t: 0, kind: 'hit', note: 'Bar 1 downbeat and loop landing: bicycle bell rings at 0.0 and 0.125 (struck metal, partials 2.6, 5.9, 7.3 kHz, 0.35 s decay); band starts: pizzicato oom-pah F2 on 1 and 3, off-beat chords, brushed small cymbal on 2 and 4, xylophone motif F5 A5 C6 A5 G5 E5 F5 on 8ths' },
      { t: 0.5, kind: 'sfx', note: 'Skid stop: band-passed noise 2.5 kHz to 700 Hz over 0.25 s with 30 Hz flutter; pizzicato plunk C3' },
      { t: 1, kind: 'sfx', note: 'Coins held up: quick xylophone C6 E6' },
      { t: 1.5, kind: 'hit', note: 'Coins slapped on the counter: three metallic clinks on 32nds (FM bells 3.8, 4.4, 5.1 kHz, 80 ms) over a 900 Hz woodblock' },
      { t: 2, kind: 'cut', note: 'Inside booth one: band low-passed at 1.5 kHz, low clarinet holds F3; burger slide zip, band noise 1.2 to 3 kHz over 120 ms' },
      { t: 2.5, kind: 'sfx', note: 'Snatch: 80 ms high-passed whoosh and pizzicato pluck C5' },
      { t: 3, kind: 'hit', note: 'Register ka-ching: bell partials 2.1 and 5.3 kHz, 0.6 s decay; drawer clatter (60 ms noise); low chunk sine 110 Hz' },
      { t: 3.5, kind: 'cut', note: 'Outside, full bandwidth; mouth opens: rising clarinet glissando C4 to C5 over 0.5 s' },
      { t: 4, kind: 'hit', note: 'Bar 3 downbeat chomp: 50 ms crunch noise 1.5 to 4 kHz, sine thock 140 to 80 Hz; pizzicato F major chord' },
      { t: 4.5, kind: 'sfx', note: 'Chewing: soft squelches on 4.5, 4.75, 5.0 (noise low-passed at 400 Hz, 60 ms)' },
      { t: 5, kind: 'sfx', note: 'Bliss: xylophone glissando F5 to F6 on 32nds, F major pentatonic; clarinet A5 with slow vibrato' },
      { t: 6, kind: 'cut', note: 'Bar 4 title stinger: whole band on F6/9 with a small-cymbal crash' },
      { t: 6.125, kind: 'sfx', note: 'BURGER, pops: xylophone A5' },
      { t: 6.25, kind: 'sfx', note: 'TWO pops: xylophone C6' },
      { t: 6.375, kind: 'sfx', note: 'PRICES pops: xylophone F6' },
      { t: 6.5, kind: 'sfx', note: 'Byline draws on: pencil scribble, band noise 3 to 6 kHz with jittered amplitude, 0.25 s' },
      { t: 7, kind: 'sfx', note: 'Burger bounce: soft pizzicato boop gliding F3 to C4' },
      // Act 2: two miles
      { t: 8, kind: 'cut', note: 'Bar 5 ride groove: walking pizzicato bass on quarters from F2, off-beat chords, xylophone ride melody on 8ths, quiet freewheel ticks on 16ths (6 kHz), brushed cymbal on 2 and 4' },
      { t: 8.5, kind: 'sfx', note: 'Mile counter steps: tiny 1.6 kHz woodblock tick on 8.5, 9.0, 9.5, 10.0, 10.5, 11.0, 11.5' },
      { t: 9, kind: 'sfx', note: 'Gulp: sine 300 to 120 Hz over 120 ms with a 25 Hz wobble' },
      { t: 10, kind: 'cut', note: 'Fountain: clarinet takes the ride melody up an octave; fountain fsssh (band noise near 4 kHz, 0.2 s) on 10.0, 10.5, 11.0' },
      { t: 11.5, kind: 'cut', note: 'Columns: brassy colour (clarinet doubled by a low-passed saw a fifth below); pizzicato run up F major on 32nds' },
      { t: 12, kind: 'hit', note: 'Two miles: single bicycle bell ring and xylophone C7' },
      { t: 12, kind: 'sfx', note: 'Sniff with the head lift: two short noise puffs' },
      { t: 12.5, kind: 'sfx', note: 'Sprint: ride melody doubles to 16ths' },
      { t: 13, kind: 'cut', note: 'Inside booth two: muffled skid outside (low-passed at 1.2 kHz); band thins to pizzicato and low clarinet' },
      { t: 13.5, kind: 'sfx', note: 'Coins jingle: three FM clinks on 16ths' },
      { t: 14, kind: 'sfx', note: 'Burger slide zip, as at 2.0' },
      { t: 14.5, kind: 'sfx', note: 'Snatch whoosh and pluck, as at 2.5, plus a coin clink' },
      { t: 15, kind: 'sfx', note: 'Two dry woodblock knocks on 15.0 and 15.125; the band stops, one clarinet note held' },
      { t: 15.25, kind: 'swell', note: 'Push-in: slide whistle sine 400 Hz to 1.6 kHz over 0.75 s, snare-like noise roll accelerating from 16ths to 32nds into 16.0' },
      // Act 3: where $6.89 comes from (D minor for the machine and the owner)
      { t: 16, kind: 'hit', note: 'Bar 9 midpoint downbeat, the $6.89 tag: shock stab on a diminished chord (B D F Ab), small-cymbal crash, low boom sine 70 to 45 Hz over 0.5 s' },
      { t: 16.125, kind: 'sfx', note: 'Eye pop boing: sine 220 Hz with 12 Hz vibrato of 40 percent, decaying over 0.5 s' },
      { t: 16.25, kind: 'sfx', note: '+21% scrawl: pencil scratch, band noise 2.5 to 5 kHz, 0.2 s; falling clarinet glissando A4 to E4' },
      { t: 16.5, kind: 'sfx', note: 'Jaw drop: low pizzicato thunk F2' },
      { t: 17, kind: 'sfx', note: 'Burger trembles: fast xylophone tremolo on E5 for 0.25 s' },
      { t: 17.625, kind: 'swell', note: 'Fade to black: band stops on a choked cymbal; only a low clarinet D2 remains, gone by 18.0' },
      { t: 18, kind: 'cut', note: 'Bar 10, the machine in D minor: woodblock tick-tock on 8ths (900 Hz, 1.2 kHz), pizzicato ostinato D3 A3 F3 A3 on 16ths, clarinet pedal D2, hum (55 Hz saw low-passed at 300 Hz, 2 Hz wobble)' },
      { t: 18.25, kind: 'sfx', note: 'Receipt stream until 20.0: rustling paper (granular band noise 2 to 6 kHz), seeded coin clinks on 16ths panned left and right; soft wood tick for caption 1' },
      { t: 18.5, kind: 'sfx', note: 'Soft wood tick for caption 2' },
      { t: 19, kind: 'sfx', note: 'Hopper gulps on 19.0 and 19.5: mechanical gulp, sine thunk 80 Hz plus a click' },
      { t: 20, kind: 'cut', note: 'Periscope view: creaky squeak (saw 300 to 900 Hz through a narrow band-pass, 0.3 s), whirr under the pan, suspended chord' },
      { t: 20.25, kind: 'sfx', note: 'Soft wood tick for the engine caption' },
      { t: 20.5, kind: 'hit', note: 'The view locks on the columns: clunk (sine 150 Hz, 40 ms, plus click) and xylophone cluster C6 D6 E6' },
      { t: 20.875, kind: 'sfx', note: 'Eyelid blink: blip, sine 1.2 kHz, 40 ms' },
      { t: 21, kind: 'cut', note: 'Gauge: ratchet clicks on 21.125, 21.25, 21.375, 21.5, pitch rising 1 to 2 kHz' },
      { t: 21.5, kind: 'hit', note: 'Needle lands on MEDIUM: small FM bell ding at 2.4 kHz; ostinato steps up to F' },
      { t: 21.75, kind: 'sfx', note: 'Printing: four typewriter clicks on 16ths 21.75 to 22.125 (3 ms high-passed noise, 1.8 kHz tick) over a paper slide' },
      { t: 22.25, kind: 'sfx', note: 'Ticket out: cold metallic FM bell ding at 1.6 kHz' },
      { t: 22.5, kind: 'cut', note: 'Inside booth two: paper flutter (noise 1 to 3 kHz, amplitude-modulated at 14 Hz, 0.25 s); score turns weary in D minor, slow pizzicato, descending clarinet line' },
      { t: 22.75, kind: 'sfx', note: 'Catch: soft paper snap' },
      { t: 23.5, kind: 'hit', note: 'Phone rings: two metal bells, partials 1.1 and 1.4 kHz, 20 Hz striker, 0.375 s burst' },
      { t: 24, kind: 'cut', note: 'Bar 13 close-up: receiver squawk, muffled voice from a 180 Hz saw with seeded wobbly pitch, band-passed 400 to 1500 Hz, syllables on 8ths to 24.375, no words' },
      { t: 24.5, kind: 'sfx', note: 'Sigh: breath noise band-passed 400 to 1200 Hz, 0.1 s attack, 0.6 s decay, falling filter; clarinet glide A4 F4 D4' },
      { t: 25, kind: 'sfx', note: 'Keys: four plastic clicks on 25.0, 25.125, 25.25, 25.375 (5 ms noise through a 2.5 kHz resonance, 120 Hz thump)' },
      { t: 25.5, kind: 'hit', note: 'Price entered: low tired register ding at 1.3 kHz and pizzicato D2' },
      // Act 4: back to $5.69 (F major)
      { t: 26, kind: 'cut', note: 'Bar 14, the street: F major returns over a held pizzicato tremolo on C' },
      { t: 26.25, kind: 'sfx', note: 'Crouch: slide whistle rising 300 to 900 Hz over 0.25 s' },
      { t: 26.5, kind: 'sfx', note: 'Turn: whistle swoop, sine 1.6 kHz down to 400 Hz over 0.2 s' },
      { t: 26.625, kind: 'hit', note: 'Dash: high-passed noise whoosh 0.25 s, pizzicato zing; fast ride-back theme starts (ride melody in 16ths)' },
      { t: 27, kind: 'cut', note: 'Cascade card 1 (columns): whip whoosh and xylophone F6' },
      { t: 27.25, kind: 'sfx', note: 'Card 2 (fountain): whip and xylophone D6' },
      { t: 27.5, kind: 'sfx', note: 'Card 3 (fences): whip and xylophone C6' },
      { t: 27.75, kind: 'sfx', note: 'Card 4 (booth one): whip, xylophone A5 and the skid' },
      { t: 27.875, kind: 'sfx', note: 'Mile counter at zero: bicycle bell ring' },
      { t: 28, kind: 'cut', note: 'Bar 15, the bite again: burger motif returns warm in F major; mouth opens on the clarinet glissando C4 to C5, as at 3.5' },
      { t: 28.25, kind: 'sfx', note: 'Same burger. pops: xylophone A5' },
      { t: 28.5, kind: 'hit', note: 'Chomp, as at 4.0' },
      { t: 28.75, kind: 'sfx', note: 'Different neighborhood. pops: xylophone C6; chewing squelches on 8ths' },
      { t: 29.5, kind: 'sfx', note: 'Bliss: xylophone glissando F5 to F6, as at 5.0' },
      { t: 30, kind: 'cut', note: 'Bar 16 sources card: closing cadence, pizzicato F2 C3 F2 on the beats, burger motif slower on xylophone, clarinet holds A4, brushed cymbal swish' },
      { t: 30.5, kind: 'sfx', note: 'Channel mark draws on: xylophone sparkle C6 E6 G6 C7 on 32nds' },
      { t: 31, kind: 'sfx', note: 'Owner yawns: soft low clarinet glide F3 down to C3' },
      { t: 31.5, kind: 'sfx', note: 'Soft final F major chord, pizzicato and xylophone, short' },
      { t: 31.75, kind: 'sfx', note: 'Pickup: xylophone C5 and E5 on 32nds, resolving onto the bell and F of the replay downbeat' },
    ],
  };
})();
